import type { AppLocale } from "../i18n/index.ts";

const localizedValueLabels: Record<AppLocale, Record<string, string>> = {
  ru: {
    full_cycle: "Полный цикл",
    assembly: "Сборка",
    contract: "Контрактное производство",
    combined: "Комбинированная модель",
    educational_and_mass_market: "Обучающие и массовые игрушки",
    toddlers: "Игрушки для малышей",
    outdoor: "Уличные игрушки",
    branded: "Брендированные игрушки",
    budget: "Бюджетный",
    middle: "Средний",
    premium: "Премиум",
    own_design: "Собственный дизайн",
    ready_molds: "Готовые формы",
    mixed_design: "Комбинированно",
    age_0_3: "0-3 года",
    age_3_6: "3-6 лет",
    age_6_12: "6-12 лет",
    age_12_plus: "12+",
    other: "Другое",
    owned: "Собственное",
    rent: "Аренда",
    searching: "В поиске",
    land_required: "Нужен участок/производственная зона",
    new: "Новое",
    used: "Б/у",
    not_selected: "Пока не выбрано",
    local: "Локальное",
    import: "Импорт",
    mixed: "Смешанная модель",
    wholesale: "Оптовики",
    bazaars: "Базары",
    supermarkets: "Магазины/супермаркеты",
    marketplaces: "Маркетплейсы",
    schools: "Детские сады/школы",
    export: "Экспорт",
    direct_b2b: "B2B-клиенты",
    retail: "Розница",
    b2b_orders: "B2B-заказы",
    delivery: "Доставка",
    walk_in: "Проходящий поток",
    students: "Студенты",
    office_workers: "Офисные сотрудники",
    events: "Мероприятия",
    uniforms: "Форма/спецодежда",
    immediate: "Сразу",
    days_7: "7 дней",
    days_15: "15 дней",
    days_30: "30 дней",
    days_60_plus: "60+ дней",
    low: "Низкий",
    medium: "Средний",
    high: "Высокий",
    aware: "Понимаю требования",
    partly_aware: "Частично понимаю",
    not_aware: "Нужна консультация",
    yes: "Да",
    no: "Нет",
    unknown: "Пока не знаю",
    calculated: "Использовать расчетную выручку",
    stable: "Использовать указанную стабильную выручку",
    none: "Не применяется",
    annuity: "Аннуитет",
    equal_principal: "Равными долями",
    user_input: "Данные пользователя",
    assumption: "Допущение",
    external_source: "Внешний источник",
    estimated: "Оценка",
    exact: "Точное совпадение",
    close_proxy: "Близкий proxy",
    broad_proxy: "Широкий proxy",
    not_found: "Не найдено",
    market_proxy: "Рыночный proxy",
    financing_gap: "Разрыв финансирования",
    financingGap: "Разрыв финансирования",
    official_statistics: "Официальная статистика",
    multilateral_statistics: "Международная статистика",
    custom_upload: "Загруженные данные",
    registry: "Реестр источников",
    note: "Примечание",
    proxy: "Proxy",
    UZS: "UZS",
    USD: "USD"
  },
  uz: {
    full_cycle: "To'liq sikl",
    assembly: "Yig'ish",
    contract: "Kontrakt ishlab chiqarish",
    combined: "Aralash model",
    educational_and_mass_market: "Ta'limiy va ommaviy o'yinchoqlar",
    toddlers: "Kichik yoshdagi bolalar uchun",
    outdoor: "Ko'cha o'yinchoqlari",
    branded: "Brendlangan o'yinchoqlar",
    budget: "Byudjet",
    middle: "O'rta",
    premium: "Premium",
    own_design: "O'z dizayni",
    ready_molds: "Tayyor qoliplar",
    mixed_design: "Aralash dizayn",
    age_0_3: "0-3 yosh",
    age_3_6: "3-6 yosh",
    age_6_12: "6-12 yosh",
    age_12_plus: "12+",
    other: "Boshqa",
    owned: "O'z mulki",
    rent: "Ijarada",
    searching: "Qidirilmoqda",
    land_required: "Yer / ishlab chiqarish maydoni kerak",
    new: "Yangi",
    used: "Ishlatilgan",
    not_selected: "Hali tanlanmagan",
    local: "Mahalliy",
    import: "Import",
    mixed: "Aralash model",
    wholesale: "Ulgurji xaridorlar",
    bazaars: "Bozorlar",
    supermarkets: "Do'konlar / supermarketlar",
    marketplaces: "Marketpleyslar",
    schools: "Bog'cha / maktablar",
    export: "Eksport",
    direct_b2b: "B2B mijozlar",
    retail: "Chakana savdo",
    b2b_orders: "B2B buyurtmalar",
    delivery: "Yetkazib berish",
    walk_in: "O'tib kiruvchi mijozlar",
    students: "Talabalar",
    office_workers: "Ofis xodimlari",
    events: "Tadbirlar",
    uniforms: "Forma / maxsus kiyim",
    immediate: "Darhol",
    days_7: "7 kun",
    days_15: "15 kun",
    days_30: "30 kun",
    days_60_plus: "60+ kun",
    low: "Past",
    medium: "O'rta",
    high: "Yuqori",
    aware: "Talablarni bilaman",
    partly_aware: "Qisman bilaman",
    not_aware: "Maslahat kerak",
    yes: "Ha",
    no: "Yo'q",
    unknown: "Hali bilmayman",
    calculated: "Hisoblangan tushumni ishlatish",
    stable: "Kiritilgan barqaror tushumni ishlatish",
    none: "Qo'llanilmaydi",
    annuity: "Annuitet",
    equal_principal: "Teng asosiy qarz",
    user_input: "Foydalanuvchi kiritgan",
    assumption: "Faraz",
    external_source: "Tashqi manba",
    estimated: "Baholangan",
    exact: "Aniq moslik",
    close_proxy: "Yaqin proxy",
    broad_proxy: "Keng proxy",
    not_found: "Topilmadi",
    market_proxy: "Bozor proxy",
    financing_gap: "Moliyalashtirish tafovuti",
    financingGap: "Moliyalashtirish tafovuti",
    official_statistics: "Rasmiy statistika",
    multilateral_statistics: "Xalqaro statistika",
    custom_upload: "Yuklangan ma'lumotlar",
    registry: "Manbalar reyestri",
    note: "Izoh",
    proxy: "Proxy",
    UZS: "UZS",
    USD: "USD"
  },
  en: {
    full_cycle: "Full cycle",
    assembly: "Assembly",
    contract: "Contract manufacturing",
    combined: "Combined model",
    educational_and_mass_market: "Educational and mass-market toys",
    toddlers: "Toddler toys",
    outdoor: "Outdoor toys",
    branded: "Branded toys",
    budget: "Budget",
    middle: "Mid-range",
    premium: "Premium",
    own_design: "Own design",
    ready_molds: "Ready molds",
    mixed_design: "Mixed design",
    age_0_3: "0-3 years",
    age_3_6: "3-6 years",
    age_6_12: "6-12 years",
    age_12_plus: "12+",
    other: "Other",
    owned: "Owned",
    rent: "Rented",
    searching: "Searching",
    land_required: "Land / production site required",
    new: "New",
    used: "Used",
    not_selected: "Not selected yet",
    local: "Local",
    import: "Import",
    mixed: "Mixed model",
    wholesale: "Wholesalers",
    bazaars: "Bazaars",
    supermarkets: "Stores / supermarkets",
    marketplaces: "Marketplaces",
    schools: "Kindergartens / schools",
    export: "Export",
    direct_b2b: "B2B clients",
    retail: "Retail",
    b2b_orders: "B2B orders",
    delivery: "Delivery",
    walk_in: "Walk-in customers",
    students: "Students",
    office_workers: "Office workers",
    events: "Events",
    uniforms: "Uniforms / workwear",
    immediate: "Immediate",
    days_7: "7 days",
    days_15: "15 days",
    days_30: "30 days",
    days_60_plus: "60+ days",
    low: "Low",
    medium: "Medium",
    high: "High",
    aware: "Understands requirements",
    partly_aware: "Partly understands",
    not_aware: "Needs consultation",
    yes: "Yes",
    no: "No",
    unknown: "Not sure yet",
    calculated: "Use calculated revenue",
    stable: "Use stated stable revenue",
    none: "Not applicable",
    annuity: "Annuity",
    equal_principal: "Equal principal",
    user_input: "User input",
    assumption: "Assumption",
    external_source: "External source",
    estimated: "Estimated",
    exact: "Exact match",
    close_proxy: "Close proxy",
    broad_proxy: "Broad proxy",
    not_found: "Not found",
    market_proxy: "Market proxy",
    financing_gap: "Financing gap",
    financingGap: "Financing gap",
    official_statistics: "Official statistics",
    multilateral_statistics: "Multilateral statistics",
    custom_upload: "Uploaded data",
    registry: "Source registry",
    note: "Note",
    proxy: "Proxy",
    UZS: "UZS",
    USD: "USD"
  }
};

export const valueLabels = localizedValueLabels.ru;

export function labelValue(value: unknown, locale: AppLocale = "ru"): string {
  const labels = localizedValueLabels[locale];
  if (Array.isArray(value)) {
    return value.length ? value.map((item) => labelValue(item, locale)).join(", ") : locale === "ru" ? "Не указано" : locale === "uz" ? "Ko'rsatilmagan" : "Not specified";
  }
  if (typeof value === "boolean") {
    return value ? labels.yes : labels.no;
  }
  if (value === null || value === undefined || value === "") {
    return locale === "ru" ? "Не указано" : locale === "uz" ? "Ko'rsatilmagan" : "Not specified";
  }
  const text = String(value);
  return labels[text] ?? text;
}

const localizedUnitLabels: Record<string, Record<AppLocale, string>> = {
  "мес.": { ru: "мес.", en: "months", uz: "oy" },
  "мес": { ru: "мес.", en: "months", uz: "oy" },
  "м2": { ru: "м²", en: "sqm", uz: "m²" },
  "ед./мес.": { ru: "ед./мес.", en: "units/month", uz: "birlik/oy" },
  "шт./мес.": { ru: "шт./мес.", en: "units/month", uz: "dona/oy" },
  "заказов/мес.": { ru: "заказов/мес.", en: "orders/month", uz: "buyurtma/oy" },
  "порций/мес.": { ru: "порций/мес.", en: "servings/month", uz: "portsiya/oy" },
  "услуг/мес.": { ru: "услуг/мес.", en: "services/month", uz: "xizmat/oy" },
  "изделий/мес.": { ru: "изделий/мес.", en: "items/month", uz: "mahsulot/oy" },
  "клиентов/мес.": { ru: "клиентов/мес.", en: "customers/month", uz: "mijoz/oy" },
  "UZS": { ru: "UZS", en: "UZS", uz: "UZS" },
  "сум": { ru: "сум", en: "UZS", uz: "UZS" },
  "%": { ru: "%", en: "%", uz: "%" }
};

export function localizeUnitLabel(unit: unknown, locale: AppLocale = "ru"): string {
  if (unit === undefined || unit === null || unit === "") return "";
  const text = String(unit);
  return localizedUnitLabels[text]?.[locale] ?? text;
}
